export const dummyListings = [
  {
    id: 1,
    slug: "rumah-modern-bsd-city",
    title: "Rumah Modern Minimalis di BSD City",
    description: "<p>Rumah modern dengan desain minimalis, lokasi strategis.</p>",
    price: "2500000000",
    currency: "IDR",
    type: "sale",
    category: "house",
    bedrooms: 4,
    bathrooms: 3,
    landArea: 150,
    buildingArea: 200,
    address: "BSD City, Tangerang Selatan",
    city: "Tangerang",
    province: "Banten",
    features: ["Swimming Pool", "Carport", "Smart Home", "Garden"],
    images: ["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800"],
    virtualTourUrl: null,
    isFeatured: true,
    status: "available",
    template: "all",
    agentId: 1,
  },
  {
    id: 2,
    slug: "apartemen-sudirman-park",
    title: "Apartemen Premium Sudirman Park",
    description: "<p>Apartemen full furnished di jantung kota Jakarta.</p>",
    price: "15000000",
    currency: "IDR",
    type: "rent",
    category: "apartment",
    bedrooms: 2,
    bathrooms: 1,
    landArea: null,
    buildingArea: 65,
    address: "Jl. KH. Mas Mansyur, Jakarta Pusat",
    city: "Jakarta",
    province: "DKI Jakarta",
    features: ["Furnished", "Gym", "Pool", "Concierge"],
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800"],
    virtualTourUrl: null,
    isFeatured: true,
    status: "available",
    template: "all",
    agentId: 1,
  },
  {
    id: 3,
    slug: "villa-ubud-bali",
    title: "Villa Mewah di Ubud Bali",
    description: "<p>Villa eksklusif dengan pemandangan sawah dan private pool.</p>",
    price: "8500000000",
    currency: "IDR",
    type: "sale",
    category: "villa",
    bedrooms: 5,
    bathrooms: 5,
    landArea: 500,
    buildingArea: 400,
    address: "Ubud, Gianyar",
    city: "Gianyar",
    province: "Bali",
    features: ["Private Pool", "Rice Field View", "Tropical Garden"],
    images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800"],
    virtualTourUrl: null,
    isFeatured: true,
    status: "available",
    template: "luxury",
    agentId: 2,
  },
  {
    id: 4,
    slug: "rumah-minimalis-jakarta-selatan",
    title: "Rumah Minimalis di Jakarta Selatan",
    description: "<p>Rumah modern dengan taman luas, cocok untuk keluarga.</p>",
    price: "3200000000",
    currency: "IDR",
    type: "sale",
    category: "house",
    bedrooms: 3,
    bathrooms: 2,
    landArea: 200,
    buildingArea: 160,
    address: "Jl. Fatmawati, Jakarta Selatan",
    city: "Jakarta",
    province: "DKI Jakarta",
    features: ["Garden", "Carport", "Security 24/7"],
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800"],
    virtualTourUrl: null,
    isFeatured: false,
    status: "available",
    template: "classic",
    agentId: 1,
  },
  {
    id: 5,
    slug: "apartemen-kuningan-city",
    title: "Apartemen Studio Kuningan City",
    description: "<p>Studio apartemen strategis dekat pusat bisnis.</p>",
    price: "8000000",
    currency: "IDR",
    type: "rent",
    category: "apartment",
    bedrooms: 1,
    bathrooms: 1,
    landArea: null,
    buildingArea: 35,
    address: "Kuningan, Jakarta Selatan",
    city: "Jakarta",
    province: "DKI Jakarta",
    features: ["Furnished", "Gym", "Pool", "Parking"],
    images: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800"],
    virtualTourUrl: null,
    isFeatured: false,
    status: "available",
    template: "modern",
    agentId: 2,
  },
  {
    id: 6,
    slug: "tanah-kavling-bandung",
    title: "Tanah Kavling Premium di Bandung",
    description: "<p>Tanah strategis cocok untuk investasi atau bangun rumah.</p>",
    price: "1200000000",
    currency: "IDR",
    type: "sale",
    category: "land",
    bedrooms: null,
    bathrooms: null,
    landArea: 300,
    buildingArea: null,
    address: "Dago, Bandung",
    city: "Bandung",
    province: "Jawa Barat",
    features: ["View Pegunungan", "Akses Jalan Raya", "Dekat Kampus"],
    images: ["https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800"],
    virtualTourUrl: null,
    isFeatured: false,
    status: "available",
    template: "classic",
    agentId: 2,
  },
];

export const dummyAgents = [
  {
    id: 1,
    name: "Budi Santoso",
    photo: null,
    phone: "+6281234567890",
    email: "budi@property.com",
    bio: "<p>Agen properti berpengalaman 10+ tahun di Jabodetabek.</p>",
    specializations: ["Rumah", "Apartemen"],
    isActive: true,
  },
  {
    id: 2,
    name: "Sari Dewi",
    photo: null,
    phone: "+6281298765432",
    email: "sari@property.com",
    bio: "<p>Spesialis properti premium dan komersial.</p>",
    specializations: ["Villa", "Komersial"],
    isActive: true,
  },
];

export const dummyTestimonials = [
  {
    id: 1,
    clientName: "Ahmad Rizki",
    clientPhoto: null,
    content: "Proses pembelian rumah sangat mudah berkat tim yang profesional.",
    rating: 5,
    template: "all",
    isActive: true,
  },
  {
    id: 2,
    clientName: "Linda Wijaya",
    clientPhoto: null,
    content: "Apartemen yang kami sewa sesuai ekspektasi. Pelayanan memuaskan.",
    rating: 4,
    template: "all",
    isActive: true,
  },
  {
    id: 3,
    clientName: "Rudi Hartono",
    clientPhoto: null,
    content: "Sangat puas dengan layanan yang diberikan. Proses cepat dan transparan.",
    rating: 5,
    template: "classic",
    isActive: true,
  },
  {
    id: 4,
    clientName: "Maya Indah",
    clientPhoto: null,
    content: "Villa yang direkomendasikan melebihi ekspektasi. Terima kasih!",
    rating: 5,
    template: "luxury",
    isActive: true,
  },
];

export const dummySiteSettings: Record<string, any> = {
  modern: {
    id: 1,
    template: "modern",
    siteName: "Properti Modern",
    logoUrl: null,
    heroTitle: "Temukan Hunian Impian Anda",
    heroSubtitle: "Koleksi properti terbaik dengan desain modern dan lokasi strategis",
    heroImage: null,
    aboutContent: "<p>Properti Modern adalah agen properti terpercaya yang berfokus pada hunian modern di area Jabodetabek. Dengan pengalaman lebih dari 10 tahun, kami telah membantu ribuan keluarga menemukan rumah impian mereka.</p><p>Kami percaya bahwa setiap keluarga berhak mendapatkan hunian yang nyaman, aman, dan sesuai dengan kebutuhan mereka.</p>",
    contactPhone: "+6281234567890",
    contactEmail: "info@propertimodern.com",
    contactAddress: "Jl. Sudirman No. 1, Jakarta",
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3966.0!2d106.8!3d-6.2!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNsKwMTInMDAuMCJTIDEwNsKwNDgnMDAuMCJF!5e0!3m2!1sen!2sid!4v1",
    socialLinks: { instagram: "https://instagram.com/propertimodern", facebook: "https://facebook.com/propertimodern" },
  },
  luxury: {
    id: 2,
    template: "luxury",
    siteName: "Luxury Estates",
    logoUrl: null,
    heroTitle: "Exclusive Living, Redefined",
    heroSubtitle: "Curated collection of the finest properties",
    heroImage: null,
    aboutContent: "<p>Luxury Estates menawarkan koleksi properti premium eksklusif untuk klien yang menghargai kualitas dan kemewahan. Dari villa tropis hingga penthouse metropolitan, kami menyediakan hunian terbaik di kelasnya.</p>",
    contactPhone: "+6281298765432",
    contactEmail: "concierge@luxuryestates.id",
    contactAddress: "Plaza Indonesia Level 5, Jakarta",
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3966.0!2d106.8!3d-6.2!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNsKwMTInMDAuMCJTIDEwNsKwNDgnMDAuMCJF!5e0!3m2!1sen!2sid!4v1",
    socialLinks: { instagram: "https://instagram.com/luxuryestates" },
  },
  classic: {
    id: 3,
    template: "classic",
    siteName: "Griya Nusantara",
    logoUrl: null,
    heroTitle: "Rumah Keluarga, Kebahagiaan Anda",
    heroSubtitle: "Properti terpercaya untuk keluarga Indonesia sejak 2010",
    heroImage: null,
    aboutContent: "<p>Griya Nusantara telah melayani keluarga Indonesia sejak 2010. Kami memahami bahwa rumah bukan sekadar bangunan, melainkan tempat tumbuhnya kebahagiaan keluarga.</p><p>Dengan pendekatan personal dan pelayanan terpercaya, kami siap membantu Anda menemukan rumah idaman.</p>",
    contactPhone: "+6281112223333",
    contactEmail: "halo@griyanusantara.id",
    contactAddress: "Jl. Gatot Subroto No. 10, Jakarta",
    mapEmbedUrl: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3966.0!2d106.8!3d-6.2!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNsKwMTInMDAuMCJTIDEwNsKwNDgnMDAuMCJF!5e0!3m2!1sen!2sid!4v1",
    socialLinks: { instagram: "https://instagram.com/griyanusantara", facebook: "https://facebook.com/griyanusantara", twitter: "https://twitter.com/griyanusantara" },
  },
};
